#!/usr/bin/env bash
#
# setup_host.sh — build the e2e fixtures that need apptainer, on the HOST (or a
# cluster login node), NOT in the slurm-docker-ci container:
#   - the repronim-containers-shim, with bids-simbids built from Docker Hub
#   - a fake BIDS input dataset generated by simbids-raw-mri
# run_in_docker.sh bind-mounts both into the container (see there), so the
# container never rebuilds them. On a real cluster the shim is built on the login
# node exactly this way, so this is the local analog of "pre-staged on the cluster
# fs" — a portable SIF runs fine under the container's singularity.
#
# Idempotent + persistent: both are built once under a fixtures dir and reused
# (the speed win — no per-run SIF pull/build).
#
# Outputs (override via env):
#   MECHABABS_E2E_FIXTURES  the fixtures dir (default /tmp/mechababs-e2e-fixtures)
#     <fixtures>/repronim-containers-shim   the shim dataset (bids-simbids)
#     <fixtures>/simbids-raw                the fake BIDS dataset
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
FIXTURES="${MECHABABS_E2E_FIXTURES:-/tmp/mechababs-e2e-fixtures}"
SHIM="$FIXTURES/repronim-containers-shim"
RAWDATA="$FIXTURES/simbids-raw"
mkdir -p "$FIXTURES"

command -v apptainer >/dev/null || { echo "need apptainer on the host" >&2; exit 1; }

# 1. Shim with bids-simbids (the script guards an existing clone/SIF, so re-runs
#    are cheap). REPRONIM points it at our fixtures dir.
REPRONIM="$SHIM" "$REPO/tmp-repronim-container-shim.sh" bids-simbids

# 2. Fake single-session (subject-level) BIDS via simbids-raw-mri, using the
#    config baked into the simbids container. simbids writes a `simbids/` subdir;
#    move it to $RAWDATA and datalad-ify so babs can clone it as raw input.
SIF="$SHIM/images/bids/bids-simbids--0.0.3.sif"
if [ ! -e "$RAWDATA/.datalad" ]; then
    gen="$(mktemp -d "$FIXTURES/gen-XXXXXX")"
    apptainer exec -B "$gen" "$SIF" simbids-raw-mri "$gen" ds005237_configs.yaml
    mv "$gen/simbids" "$RAWDATA"
    /usr/bin/rm -rf "$gen"
    datalad create --force "$RAWDATA"
    datalad save -d "$RAWDATA" -m "simbids-raw-mri ds005237 (fake single-session BIDS)"
fi

echo "shim:    $SHIM  (bids-simbids)" >&2
echo "rawdata: $RAWDATA" >&2
